version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: redteaming-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME:-redteaming}
      MYSQL_USER: ${DB_USER:-redteam}
      MYSQL_PASSWORD: ${DB_PASSWORD:-redteampassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - redteaming-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    image: redteaming-toolkit/backend
    container_name: redteaming-backend
    hostname: backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app/backend
      - ssl_certs:/app/backend/certificates
    env_file:
      - ../.env
    environment:
      - DB_HOST=db
      - STORAGE_MODE=db
      - FLASK_ENV=production
      - API_KEY=redteam-production-api-key
    restart: unless-stopped
    privileged: true  # Necessary for running commands with elevated privileges
    depends_on:
      db:
        condition: service_healthy
    networks:
      redteaming-network:
        aliases:
          - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:5000/api/system/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    image: redteaming-toolkit/frontend
    container_name: redteaming-frontend
    hostname: frontend
    ports:
      - "3000:3000"
    volumes:
      - ssl_certs:/etc/nginx/ssl
    env_file:
      - ../.env
    environment:
      - REACT_APP_API_URL=https://backend:5000/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      redteaming-network:
        aliases:
          - frontend

networks:
  redteaming-network:
    driver: bridge 

volumes:
  mysql_data:
    driver: local
  ssl_certs:
    driver: local 